name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: HarryDevOps1019
          output: github-contribution-grid-snake.svg  # fixed 'output' param, no 'dist' folder
    
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: .    # push from root where svg is generated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
